# Generated by Django 5.0 on 2023-12-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
