# Generated by Django 5.0 on 2023-12-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_artist_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='cover',
            field=models.ImageField(default='', upload_to='', verbose_name='artist/covers/'),
            preserve_default=False,
        ),
    ]
